### ISSUE TITLE
HAMi exploration

### ISSUE THREAD

**Issue by mamy-CS** [mamy-CS/nvidia-k8s-mps-experiments#10]
### Project Overview
HAMi provides a Kubernetes-native solution to virtualize and share heterogeneous AI devices (e.g. GPU, NPU, MLU, DCU) across multiple workloads. It enables fine-grained, isolated allocation of compute cores and memory without needing application changes.

```console
$ kubectl get pods -n kube-system
NAME                                         READY   STATUS    RESTARTS   AGE
hami-device-plugin-k258f                     2/2     Running   0          2m5s
hami-scheduler-5c69f6c8df-wggwm              2/2     Running   0          2m5s
```
### How HAMi Works: Architecture & Flow
1. Pod Specification - Users request resources via K8s pod specs using standard & extended resource keys:
      - _nvidia.com/gpu_
      - _nvidia.com/gpumem_
      - _nvidia.com/gpucores_
2. Mutating Admission Webhook - HAMi intercepts pod creation and mutates the pod spec to:
      - Assign schedulerName: hami-scheduler
      - Add necessary annotations for device allocation.
3. Scheduler Extender - Works alongside the default scheduler or custom schedulers (e.g. [Volcano](https://github.com/Project-HAMi/volcano-vgpu-device-plugin?tab=readme-ov-file)).
      - Makes intelligent placement decisions considering:
      - GPU availability and topology
      - Current vGPU allocations on each node
      - User-defined scheduling policies (bin-pack / spread)
      - Returns the best node + device plan.
4. Device Plugin - HAMi device plugin registers virtual devices (vGPUs) with kubelet.
      - After scheduling, it:
          - Maps physical device slices to the container.
          - Exposes them through device files and environment variables.
5. HAMi-core Daemon - A small agent (libvgpu.so) is injected or mounted into the container runtime.
      - Hooks into AI runtime libraries (e.g., CUDA libcudart).
      - Enforces resource limits (compute and memory) by:
          - Blocking or throttling calls beyond the allocated amount.
          - Providing fake device visibility (e.g., only N SMs, only X GB mem).

### Key Architectural Components Summary 
Mutating Webhook - Redirects pods to HAMi scheduler, injects annotations
Scheduler Extender - Device-aware scheduling decisions
Device Plugin - Maps vGPUs to containers
HAMi-core - In-container enforcer for compute + memory limit

### Example pod deployment 1
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:22.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1 # declare how many physical GPUs the pod needs
          nvidia.com/gpumem: 3000 # 3000M GPU memory each physical GPU allocates to the pod （Optional,Integer）
          nvidia.com/gpucores: 30 # 30% GPU GPU core each physical GPU allocates to the pod （Optional,Integer)
```
```console
kubectl exec -it gpu-pod -- bash
```
```console
nvidia-smi
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.08             Driver Version: 550.127.08     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-PCIE-40GB          Off |   00000000:0F:00.0 Off |                    0 |
| N/A   40C    P0             35W /  250W |       0MiB /   3000MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

### Example pod deployment 2 - GPU burn
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: hami-pod-gpuburn
spec:
  containers:
    - name: gpu-burn
      image: quay.io/mmunirab/gpu-burn:cuda12.2-built
      command: ["/bin/bash", "-c", "--"]
      args:
        - |
          ./gpu_burn 1000
      resources:
        limits:
          nvidia.com/gpu: 1 # declare how many physical GPUs the pod needs
          nvidia.com/gpumem: 3000 # 3000M GPU memory each physical GPU allocates to the pod （Optional,Integer）
          nvidia.com/gpucores: 30 # 30% GPU GPU core each physical GPU allocates to the pod （Optional,Integer)
```
```console
nvidia-smi
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.08             Driver Version: 550.127.08     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-PCIE-40GB          Off |   00000000:0E:00.0 Off |                    0 |
| N/A   40C    P0             38W /  250W |       1MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A100-PCIE-40GB          Off |   00000000:0F:00.0 Off |                    0 |
| N/A   64C    P0            248W /  250W |    2995MiB /  40960MiB |    100%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    1   N/A  N/A    375139      C   ./gpu_burn                                   2986MiB |
+-----------------------------------------------------------------------------------------+
```
- Inside the container
```console
kubectl exec -it hami-pod-gpuburn -- bash
```
```console
nvidia-smi
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.08             Driver Version: 550.127.08     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-PCIE-40GB          Off |   00000000:0F:00.0 Off |                    0 |
| N/A   69C    P0            252W /  250W |    2569MiB /   3000MiB |    100%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+
```
